import { Link } from "react-router-dom";
import { PageShell } from "../components/PageShell";
import { SectionEyebrow } from "../components/SectionEyebrow";
import { Button } from "../components/Button";

export function BlogArticle() {
  const schema = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline:
      "The Experience Instability Trap™: Why Your Practice Is Struggling Even When Clinical Care Is Excellent",
    author: { "@type": "Person", name: "Jennifer Radu" },
    publisher: {
      "@type": "Organization",
      name: "Patient eXperience Consulting®",
    },
    datePublished: "2025-06-03",
  };
  return (
    <PageShell
      title="The Experience Instability Trap™ | PXC"
      description="Why medical practices struggle despite excellent clinical care—and the systems path out."
      heading="The Experience Instability Trap™: Why Your Practice Is Struggling Even When Clinical Care Is Excellent"
      eyebrow="PRACTICE STABILITY / PXC INSIGHTS"
      schema={schema}
      opening="The Experience Instability Trap™ is the cycle of leadership overwhelm, staff disengagement, and operational chaos that creates inconsistent patient experiences even when clinical quality is high."
    >
      <article className="article-body">
        <p className="answer-callout">
          The trap is not a people problem or a technology problem. It is a
          systems problem generated by leadership strain, cultural friction, and
          operational chaos—and system problems have system solutions.
        </p>
        <h2>What is the Experience Instability Trap™?</h2>
        <p>
          Picture a practice with talented providers and good clinical outcomes,
          yet 3.2-star reviews, 40% turnover, and a schedule that falls 25
          minutes behind every morning. The clinical work is excellent; the
          operating system around it is unstable.
        </p>
        <h2>The three forces that compound</h2>
        <div className="detail-grid">
          <div className="content-card">
            <SectionEyebrow>FORCE 01</SectionEyebrow>
            <h3>Leadership strain</h3>
            <p>
              When every staffing, scheduling, vendor, and escalation decision
              flows to one owner, strategic capacity disappears into
              firefighting.
            </p>
          </div>
          <div className="content-card">
            <SectionEyebrow>FORCE 02</SectionEyebrow>
            <h3>Cultural friction</h3>
            <p>
              When expectations and support are unclear, staff disengagement
              becomes the patient experience patients can feel.
            </p>
          </div>
          <div className="content-card">
            <SectionEyebrow>FORCE 03</SectionEyebrow>
            <h3>Operational chaos</h3>
            <p>
              When a practice depends on one heroic employee's memory, every
              absence becomes a service failure.
            </p>
          </div>
        </div>
        <h2>Why clinical excellence does not protect the practice</h2>
        <p>
          Patients tolerate operational friction because they trust the
          clinician—until the accumulated wait times, confusing handoffs, and
          cold interactions cross a threshold. Clinical excellence is the
          foundation. It is not the building.
        </p>
        <h2>The systematic exit</h2>
        <p>
          The Unified PXC System™ addresses leadership, culture, and operations
          as one connected system: VIBE-Coded Practice Blueprint™ diagnoses the
          pattern, IMPACT System™ sets the plan, the Puzzle Pyramid deploys
          changes, and the PX Cycle sustains them.
        </p>
        <p>
          <Link to="/practice-stability-scorecard">
            Take the two-minute Practice Stability Scorecard™
          </Link>{" "}
          to identify where instability is generating the most friction.
        </p>
        <Button to="/strategy-session">
          Book a Puzzle Pyramid™ Strategy Session
        </Button>
      </article>
    </PageShell>
  );
}
